spring:
  # RDB 연결
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kafka_msa?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
    username: root
    password: 1234
  # 공통 JPA 설정 (각 서비스에서 Override 가능)
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

# 공통 로깅 설정
logging:
  level:
    root: INFO
    # 전체 애플리케이션의 기본 로그 레벨 INFO: 일반 정보성 로그
    # TRACE < DEBUG < INFO < WARN < ERROR
    # 실무: 운영은 INFO, 개발은 DEBUG
    org.springframework.web: INFO # Debugging 필요할 떄만 DEBUG
    org.springframework.cloud: INFO # Debugging 필요할 떄만 DEBUG
