spring:
  application:
    name: notification-service
  profiles:
    active: local
  config:
    import: "configserver:http://localhost:8000"

  # cloud config
  cloud:
    config:
      fail-fast: true # config server ?? ?? ? ?? ??